/** Auto-generated by scripts/sync-case-images.py — do not edit by hand. */

export type CaseImageSet = {
  cover: string;
  gallery: string[];
};

export const caseImageMap: Record<number, CaseImageSet> = {
  1: {
    cover: "/images/cases/1/01.jpg",
    gallery: ["/images/cases/1/01.jpg", "/images/cases/1/02.jpg", "/images/cases/1/03.jpg", "/images/cases/1/04.jpg", "/images/cases/1/05.jpg", "/images/cases/1/06.jpg", "/images/cases/1/07.jpg", "/images/cases/1/08.jpg", "/images/cases/1/09.jpg", "/images/cases/1/10.jpg", "/images/cases/1/11.jpg", "/images/cases/1/12.jpg", "/images/cases/1/13.jpg", "/images/cases/1/14.jpg", "/images/cases/1/15.jpg", "/images/cases/1/16.jpg"],
  },
  2: {
    cover: "/images/cases/2/01.png",
    gallery: ["/images/cases/2/01.png", "/images/cases/2/02.png", "/images/cases/2/03.png", "/images/cases/2/04.png", "/images/cases/2/05.png", "/images/cases/2/06.png", "/images/cases/2/07.png"],
  },
  3: {
    cover: "/images/cases/3/01.jpg",
    gallery: ["/images/cases/3/01.jpg"],
  },
  4: {
    cover: "/images/cases/4/01.jpg",
    gallery: ["/images/cases/4/01.jpg", "/images/cases/4/02.jpg", "/images/cases/4/03.jpg", "/images/cases/4/04.jpg", "/images/cases/4/05.jpg", "/images/cases/4/06.jpg", "/images/cases/4/07.jpg", "/images/cases/4/08.jpg", "/images/cases/4/09.jpg", "/images/cases/4/10.jpg", "/images/cases/4/11.jpg", "/images/cases/4/12.jpg", "/images/cases/4/13.jpg", "/images/cases/4/14.jpg", "/images/cases/4/15.jpg", "/images/cases/4/16.jpg", "/images/cases/4/17.jpg", "/images/cases/4/18.png", "/images/cases/4/19.png"],
  },
  5: {
    cover: "/images/cases/5/01.png",
    gallery: ["/images/cases/5/01.png", "/images/cases/5/02.png", "/images/cases/5/03.png", "/images/cases/5/04.png", "/images/cases/5/05.png", "/images/cases/5/06.png", "/images/cases/5/07.png", "/images/cases/5/08.png", "/images/cases/5/09.png", "/images/cases/5/10.png", "/images/cases/5/11.png"],
  },
  6: {
    cover: "/images/cases/6/01.png",
    gallery: ["/images/cases/6/01.png", "/images/cases/6/02.png", "/images/cases/6/03.png", "/images/cases/6/04.png", "/images/cases/6/05.png", "/images/cases/6/06.png", "/images/cases/6/07.png", "/images/cases/6/08.png"],
  },
};

export function getCaseImages(id: number): CaseImageSet | undefined {
  return caseImageMap[id];
}
