"""Copy case images from source folders into public/images/cases/{id}/."""
from __future__ import annotations

import json
import os
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = Path(r"C:\Users\Administrator\Desktop\dbsource\图片\工程案例")
DEST = ROOT / "public" / "images" / "cases"
OUT_TS = ROOT / "data" / "case-images.ts"

# case id -> folder keyword(s), first match wins
CASE_FOLDER_KEYS: dict[int, list[str]] = {
    1: ["AK Live House"],
    2: ["YoYo Music"],
    3: ["乐山师范学院", "迎新晚会"],
    4: ["城市声场"],
    5: ["彝族新年"],
    6: ["第一中学", "百年校庆"],
}

IMG_EXT = {".jpg", ".jpeg", ".png", ".webp"}


def natural_key(name: str) -> list:
    return [int(p) if p.isdigit() else p.lower() for p in re.split(r"(\d+)", name)]


def find_folder(keys: list[str]) -> Path | None:
    for name in os.listdir(SOURCE):
        full = SOURCE / name
        if not full.is_dir():
            continue
        if any(k in name for k in keys):
            return full
    return None


def list_images(folder: Path) -> list[Path]:
    files = [p for p in folder.iterdir() if p.suffix.lower() in IMG_EXT]
    return sorted(files, key=lambda p: natural_key(p.name))


def sync_case(case_id: int, keys: list[str]) -> dict | None:
    folder = find_folder(keys)
    if not folder:
        print(f"WARN case {case_id}: no folder for {keys}")
        return None

    images = list_images(folder)
    if not images:
        print(f"WARN case {case_id}: empty folder {folder.name}")
        return None

    case_dir = DEST / str(case_id)
    if case_dir.exists():
        shutil.rmtree(case_dir)
    case_dir.mkdir(parents=True)

    urls: list[str] = []
    for i, src in enumerate(images, start=1):
        ext = src.suffix.lower()
        if ext == ".jpeg":
            ext = ".jpg"
        dest_name = f"{i:02d}{ext}"
        shutil.copy2(src, case_dir / dest_name)
        urls.append(f"/images/cases/{case_id}/{dest_name}")

    cover = urls[0]
    print(f"case {case_id}: {len(urls)} images from {folder.name}")
    return {"cover": cover, "gallery": urls}


def write_ts(mapping: dict[int, dict]) -> None:
    lines = [
        "/** Auto-generated by scripts/sync-case-images.py — do not edit by hand. */",
        "",
        "export type CaseImageSet = {",
        "  cover: string;",
        "  gallery: string[];",
        "};",
        "",
        "export const caseImageMap: Record<number, CaseImageSet> = {",
    ]
    for cid in sorted(mapping):
        item = mapping[cid]
        gallery = json.dumps(item["gallery"], ensure_ascii=False)
        lines.append(f"  {cid}: {{")
        lines.append(f'    cover: "{item["cover"]}",')
        lines.append(f"    gallery: {gallery},")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("export function getCaseImages(id: number): CaseImageSet | undefined {")
    lines.append("  return caseImageMap[id];")
    lines.append("}")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    mapping: dict[int, dict] = {}
    for case_id, keys in CASE_FOLDER_KEYS.items():
        result = sync_case(case_id, keys)
        if result:
            mapping[case_id] = result

    # 3.28 乌兰浩特乐队案例照片 -> merge into case 4 gallery
    extra_folder = None
    for name in os.listdir(SOURCE):
        if name.startswith("3.28") and (SOURCE / name).is_dir():
            extra_folder = SOURCE / name
            break
    if extra_folder and 4 in mapping:
        extra_imgs = list_images(extra_folder)
        case_dir = DEST / "4"
        start = len(mapping[4]["gallery"]) + 1
        extra_urls: list[str] = []
        for i, src in enumerate(extra_imgs, start=start):
            ext = src.suffix.lower()
            if ext == ".jpeg":
                ext = ".jpg"
            dest_name = f"{i:02d}{ext}"
            shutil.copy2(src, case_dir / dest_name)
            extra_urls.append(f"/images/cases/4/{dest_name}")
        mapping[4]["gallery"] = mapping[4]["gallery"] + extra_urls
        print(f"case 4: +{len(extra_urls)} images from {extra_folder.name}")

    write_ts(mapping)
    print(f"Wrote {OUT_TS}")


if __name__ == "__main__":
    main()
